// Generated by https://quicktype.io

export interface PlacesResponse {
	type: string;
	query: string[];
	features: FeatureFormat[];
	attribution: string;
}

export interface FeatureFormat {
	id: string;
	type: string;
	place_type: string[];
	relevance: number;
	properties: Properties;
	text_es: string;
	place_name_es: string;
	text: string;
	place_name: string;
	center: number[];
	geometry: Geometry;
	context: Context[];
}

export interface Context {
	id: string;
	text_es: string;
	text: string;
	wikidata?: Wikidata;
	language_es?: Language;
	language?: Language;
	short_code?: ShortCode;
}

export enum Language {
	Es = "es",
}

export enum ShortCode {
	Co = "co",
	CoAnt = "CO-ANT",
}

export enum Wikidata {
	Q123304 = "Q123304",
	Q48278 = "Q48278",
	Q739 = "Q739",
}

export interface Geometry {
	coordinates: number[];
	type: string;
}

export interface Properties {
	foursquare: string;
	landmark: boolean;
	address: string;
	category: string;
}
